# Theme
# ---------------------------------------------------------------------------------------

# You can uncomment `theme` above and replace it with `remote_theme` here iff you are using the 
# `jekyll-remote-theme` plugin (which is the case when using the legacy GitHub Pages pipeline).
# This will fetch the `v9` branch of the public Hydejack repository on GitHub.
remote_theme: hydecorp/hydejack@v9